ALTER TABLE USER DROP CONSTRAINT UNQ_USER_4
ALTER TABLE TICTUNNEL DROP CONSTRAINT UNQ_TICTUNNEL_5
ALTER TABLE TICTUNNEL DROP CONSTRAINT UNQ_TICTUNNEL_11
ALTER TABLE USER_TICTUNNEL DROP CONSTRAINT FK_USER_TICTUNNEL_User_ID
ALTER TABLE USER_TICTUNNEL DROP CONSTRAINT FK_USER_TICTUNNEL_tunnels_ID
DROP TABLE USER
DROP TABLE TICTUNNEL
DROP TABLE USER_TICTUNNEL
